# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cdbffa8ace352d6f8a82cdb728e6afad73c72d2451c22ae801cf634c579ff66a7bbb1b338334fba4fcc39afb651d63fd81cc38b6c2adf69fa8cfe19a1e6f751

test:
  secret_key_base: 7fb99f08aed141c7f435fb903e0118bd8da5b035ea771937424f84be3db7fef4612bd9c12b826e970e9b4456b4ec52a38ad0f7da6b5945b407bfc733f11ba008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
